#!/bin/sh
# Load functions and variables
. /usr/bin/common

cat << "EOF"
This bootstraps your device with Procursus 1800/1900

The keyboard layout is in American Qwerty.
Your iDevice's default password is alpine.
Press Ctrl + C to quit.

EOF

# Execute script
iproxy 28604 44 & \ 
scp -P28604 -o "StrictHostKeyChecking no" -o "UserKnownHostsFile=/dev/null" /bin/deploy.sh root@127.0.0.1:/private/var/root 
iproxy 28604 44 & \ 
ssh root@127.0.0.1 -P28604 -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" "cd /var/root && ./deploy.sh"