#!/bin/sh
# Load functions and variables
. /usr/bin/common

cat << "EOF"
This bootstraps your device with Procursus 1800/1900

The keyboard layout is in American Qwerty.
Your iDevice's default password is alpine.
Press Ctrl + C to quit.

EOF
IPROXY=$(iproxy 28605 44 >/dev/null 2>&1 & echo $!)
# Execute script

scp -P28605 -o "StrictHostKeyChecking no" -o "UserKnownHostsFile=/dev/null" /bin/deploy-rootless.sh root@127.0.0.1:/private/var/root 

ssh root@127.0.0.1 -p28605 -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" "cd /var/root && ./deploy-rootless.sh"