#!/bin/sh
# Load functions and variables
. /usr/bin/common


# Execute script
iproxy 28605 44 & \ 
scp -O -P28605 -o "StrictHostKeyChecking no" -o "UserKnownHostsFile=/dev/null" /usr/local/bin/deploy.sh root@127.0.0.1:/private/var/root & ssh root@localhost -p28605 -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" "cd /var/root && ./deploy.sh"

sleep 2
echo ''
enter_to_quit