#!/usr/bin/env sh

prompt() {
  printf '%s' "$1"
  read -r "$2"
}

cat << "EOF"
Connect your iDevice to this computer

The keyboard layout is in American Qwerty.
Your iDevice's users are `root` and `mobile`.
Your iDevice's default port is 22.

EOF
prompt 'User: ' user
prompt 'Port: ' port

clear

echo 'SSHing into your iDevice...'
ssh -o "ProxyCommand=inetcat $port" -o "UserKnownHostsFile=/dev/null" $user@iPhone || \
echo 'Failed to SSH into your iDevice.' >&2
