#!/bin/bash
# Load functions and variables
. /usr/bin/common
arg=$(cat /usr/bin/.args)
args=$(echo $arg)
jbt=$(cat /usr/bin/.jbtype)
jbtype=$(echo $jbt)

export NEWT_COLORS='root=,black
border=white,black
title=white,black
roottext=red,black
window=red,black
textbox=white,black
button=black,green
compactbutton=white,black
listbox=white,black
actlistbox=black,white
actsellistbox=black,green
checkbox=green,black
actcheckbox=black,green
'

whiptail_height="$(($(tput lines) - 6))"
whiptail_width="$(($(tput cols) - 20))"

if [ "$jbtype" = "Rootless" ]; then
while true; do
  CHOICE="$(whiptail --nocancel --title "palera1n | use arrow keys" --menu \
    "
  Jailbreak Type: $jbtype
  Arguments: $args" $whiptail_height $whiptail_width 8 \
    '1' 'Start' \
    '2' 'Options' \
    '3' 'Switch' \
    '4' 'Exit' 3>&1 1>&2 2>&3)"
  case "$CHOICE" in
    1)
      clear
      printf 'test'
      /usr/local/bin/palera1n $args
      sleep 2
      echo ''
      enter_to_quit
      /usr/bin/palera1n_menu
      ;;
    2)
      clear
      /usr/bin/palera1n_options
      ;;
    3)
      clear
      /usr/bin/palera1n_switch
      ;;
    4)
      clear
      /usr/bin/palen1x_menu
      ;;
  esac
done
elif [ "$jbtype" = "Rootful" ]; then
while true; do
  CHOICE="$(whiptail --nocancel --title "palera1n | use arrow keys" --menu \
    "
  Jailbreak Type: $jbtype
  Arguments: -f $args" $whiptail_height $whiptail_width 8 \
    '1' 'Start' \
    '2' 'Options' \
    '3' 'Switch' \
    '4' 'Exit' 3>&1 1>&2 2>&3)"
  case "$CHOICE" in
    1)
      clear
      ProductType=$(ideviceinfo -k ProductType)
      CPUArchitecture=$(ideviceinfo -k CPUArchitecture > /dev/null)
      ProductVersion=$(ideviceinfo -k ProductVersion > /dev/null)
      BuildVersion=$(ideviceinfo -k BuildVersion > /dev/null)
      echo '#'
      echo '# palera1n-c 2.0.0'
      echo '#'
      echo '#======== Made by ======='
      echo '# Made with <3 by Nebula, Mineek, Nathan, llsc12, Ploosh,'
      echo '# Nick Chan, and the amazing developers of checkra1n!'
      echo '#=== Troubleshooting ===='
      echo '# - If you encounter lockdownd errors make sure to'
      echo '# unlock your device and replug.'
      echo "# - Debug Info: ${GREEN}$ProductType${NORMAL} (${GREEN}$CPUArchitecture${NORMAL}) | ${GREEN}$ProductVersion${NORMAL} (${GREEN}$BuildVersion${NORMAL})"
      echo '#========================'
      echo ''
      /usr/local/bin/palera1n -f $args
      sleep 2
      echo '#========================'
      echo "# - Debug Info: ${GREEN}$ProductType${NORMAL} (${GREEN}$CPUArchitecture${NORMAL}) | ${GREEN}$ProductVersion${NORMAL} (${GREEN}$BuildVersion${NORMAL})"
      echo '#========================'
      echo ''
      enter_to_quit
      /usr/bin/palera1n_menu
      echo "Do 'exit' after you're done."
      ;;
    2)
      clear
      /usr/bin/palera1n_options
      ;;
    3)
      clear
      /usr/bin/palera1n_switch
      ;;
    4)
      clear
      /usr/bin/palen1x_menu
      ;;
  esac
done
fi
