name: Build palen1x

on:
  workflow_dispatch:
    inputs:
      version:
        description: "palera1n tag"
        required: true
        type: string
      release:
        description: "Release?"
        required: true
        default: false
        type: boolean
  push:
    tags:
      - v*

env:
  TAG: ${{ github.event.inputs.version || github.ref_name }}
  IS_RELEASE: ${{ github.event.inputs.release || (github.event_name == 'push' && 'true') }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [ x86_64, x86 ]

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (apt)
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static wget gawk debootstrap mtools xorriso ca-certificates curl libusb-1.0-0-dev gcc make gzip xz-utils unzip libc6-dev

      - name: Download palera1n resources
        run: |
          URL_BASE="https://github.com/palera1n/palera1n/releases/download/${{ env.TAG }}"

          if curl -fL -o resources/palera1n.tar.gz "$URL_BASE/palera1n-linux-${{ matrix.arch }}.tar.gz"; then
            echo "Downloaded palera1n.tar.gz"
          elif curl -fL -o resources/palera1n "$URL_BASE/palera1n-linux-${{ matrix.arch }}"; then
            echo "Downloaded palera1n"
            chmod +x resources/palera1n
          else
            exit 1
          fi

      - name: Build
        env:
          ARCH: ${{ matrix.arch }}
          VERSION: ${{ env.TAG }}
        run: |
          sudo -E ./build.sh

      - name: Create Release
        if: ${{ env.IS_RELEASE == 'true' || env.IS_RELEASE == true }}
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65
        with:
          name: ${{ env.TAG }}
          tag_name: ${{ env.TAG }}
          files: |
            work/palen1x-${{ env.TAG }}-${{ matrix.arch }}.iso
          generate_release_notes: true
          fail_on_unmatched_files: true
          draft: true
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}