name: Build palen1x

on:
  push:
    tags:
      - 'v*'

env:
  TAG: ${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, x86]

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (apt)
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static wget gawk debootstrap mtools xorriso ca-certificates curl libusb-1.0-0-dev gcc make gzip xz-utils unzip libc6-dev

      - name: Download palera1n resources
        run: |
          URL_BASE="https://github.com/palera1n/palera1n/releases/download/${{ env.TAG }}"

          if curl -fL -o resources/palera1n.tar.gz "$URL_BASE/palera1n-linux-${{ matrix.arch }}.tar.gz"; then
            echo "Downloaded palera1n.tar.gz"
          elif curl -fL -o resources/palera1n "$URL_BASE/palera1n-linux-${{ matrix.arch }}"; then
            echo "Downloaded palera1n"
            chmod +x resources/palera1n
          else
            exit 1
          fi

      - name: Build
        env:
          ARCH: ${{ matrix.arch }}
          VERSION: ${{ env.TAG }}
        run: |
          sudo -E ./build.sh

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download palen1x x86_64 ISO
        uses: actions/download-artifact@v4
        with:
          name: palen1x-${{ env.TAG }}-x86_64.iso
          path: dist/

      - name: Download palen1x x86 ISO
        uses: actions/download-artifact@v4
        with:
          name: palen1x-${{ env.TAG }}-x86.iso
          path: dist/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.TAG }}
          tag_name: ${{ env.TAG }}
          files: dist/*
          generate_release_notes: true
          fail_on_unmatched_files: true
          body: |
            https://github.com/palera1n/palera1n/releases/tag/${{ env.TAG }}

            ## Files

            `palen1x-${{ env.TAG }}-x86_64.iso`: for 64-bit computers
            `palen1x-${{ env.TAG }}-x86.iso`: for 32-bit computers
          draft: true
          token: ${{ github.token }}